### ISSUE TITLE
zigbee-shepherd node fails to deploy

### ISSUE THREAD

**Issue by condemil** [hobbyquaker/node-red-contrib-zigbee#1]
I have completely empty node-red installation and I want to try zigbee-shepherd plugin. When I am trying to add and deploy zigbee shepherd node I get the following error:

```
27 Jan 11:59:19 - [error] [zigbee-shepherd:zigbee shepherd] Error: ENOENT: no such file or directory, open '/data/zigbee/e46dcccc.8871e/names.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at new ZigbeeShepherd (/data/node_modules/node-red-contrib-zigbee/nodes/shepherd.js:148:50)
    at createNode (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)
    at Flow.start (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:67:31)
    at start (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:328:29)
    at /usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:164:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
27 Jan 11:59:19 - [info] Started flows
27 Jan 11:59:19 - [red] Uncaught Exception:
27 Jan 11:59:19 - Error: ENOENT: no such file or directory, open '/data/zigbee/e46dcccc.8871e/dev.db'
```

**Comment by condemil** [comment]
You probably want to check that file exists, and if not, create directories and file
in here: https://github.com/hobbyquaker/node-red-contrib-zigbee/blob/c37056ed43c8d0b30c2b3638cf1f96e86e0209a0/nodes/shepherd.js#L139
and here: https://github.com/hobbyquaker/node-red-contrib-zigbee/blob/c37056ed43c8d0b30c2b3638cf1f96e86e0209a0/nodes/shepherd.js#L176

**Comment by hobbyquaker** [comment]
the first error (`names.json`) does not really matter, the readFile is try/catched. The second (`dev.db`) makes me wonder - I thought zigbee-shepherd takes care of creating the directory if neccessary. Will check and fix that asap.
