### ISSUE TITLE
Allow Zigbee Converter to get/set state of groups

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/node-red-contrib-zigbee#104]
As described in "https://www.zigbee2mqtt.io/information/groups.html"
Controlling a group is similar to controlling a single device. For example to turn on all devices that are part of group send a MQTT message to `zigbee2mqtt/[GROUP_FRIENDLY_NAME]/set` with payload:`{ "state": "ON" }`

If I send similar to the Zigbee Converter Node I get the error:
```
TypeError: Cannot read property 'endpoint' of undefined
    at ZigbeeConverter.on [as _inputCallback] (/usr/local/addons/redmatic/lib/node_modules/node-red-contrib-zigbee/nodes/converter.js:148:34)
    at ZigbeeConverter.Node._emitInput (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate._onImmediate (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

With the command node the state of a group can be set, but not read.

**Comment by opajonk** [comment]
Same here, would be nice to have this!

**Comment by polo89** [comment]
Same here, cmdType read from group ends in "Error: Group undefined not found"
