### ISSUE TITLE
cannot install this pluing on a Virtual Machine based installation on an x86 architecture.

### ISSUE THREAD

**Issue by papperone** [hobbyquaker/node-red-contrib-zigbee#12]
I use NoderRed instance as container inside Home Assistant (hass.io) and this last one is installed on my NAS as a Virtual Machine.
I'vo no problems installing any other nodes but this one gives an error:

2019-04-22T04:55:47.783Z [err] install
2019-04-22T04:55:47.783Z [err]  No prebuilt binaries found (target=10.14.2 runtime=node arch=x64 libc=musl platform=linux)
2019-04-22T04:55:50.484Z [err] gyp
2019-04-22T04:55:50.486Z [err]  
2019-04-22T04:55:50.486Z [err] ERR!
2019-04-22T04:55:50.487Z [err]  
2019-04-22T04:55:50.487Z [err] build error

PS: on the exact same VM zigbee2mqtt is happily running so I guess these nodes shoudl do as well!

**Comment by hobbyquaker** [comment]
Hmm, that's strange. If zigbee2mqtt install succeeds it "should" also work with node-red-contrib-zigbee as they have the same dependencies. The error log isn't very helpful, are these all
messages it printed?

**Comment by papperone** [comment]
I tried again latest version 0.7.1 and below the whole log:

-----------------------------------------------------------
2019-05-03T12:43:37.069Z Install : @clysema/node-red-contrib-ui-week-schedule 0.1.0

2019-05-03T12:43:36.560Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production @clysema/node-red-contrib-ui-week-schedule@0.1.0
2019-05-03T12:44:12.318Z [out] + @clysema/node-red-contrib-ui-week-schedule@0.1.0
2019-05-03T12:44:12.318Z [out] added 2 packages from 10 contributors in 29.917s
2019-05-03T12:44:12.388Z rc=0

-----------------------------------------------------------
2019-05-03T12:44:50.881Z Install : node-red-contrib-zigbee 0.7.1

2019-05-03T12:44:50.209Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-zigbee@0.7.1
2019-05-03T12:46:02.760Z [out] 
2019-05-03T12:46:02.760Z [out] > @serialport/bindings@2.0.7 install /config/node-red/node_modules/cc-znp/node_modules/@serialport/bindings
2019-05-03T12:46:02.760Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2019-05-03T12:46:02.760Z [out] 
2019-05-03T12:46:04.608Z [err] prebuild-install
2019-05-03T12:46:04.611Z [err]  
2019-05-03T12:46:04.613Z [err] WARN
2019-05-03T12:46:04.618Z [err]  
2019-05-03T12:46:04.619Z [err] install
2019-05-03T12:46:04.620Z [err]  No prebuilt binaries found (target=10.14.2 runtime=node arch=x64 libc=musl platform=linux)
2019-05-03T12:46:09.114Z [err] gyp
2019-05-03T12:46:09.116Z [err]  
2019-05-03T12:46:09.117Z [err] ERR!
2019-05-03T12:46:09.117Z [err]  
2019-05-03T12:46:09.117Z [err] build error
2019-05-03T12:46:09.118Z [err]  
2019-05-03T12:46:09.119Z [err] gyp
2019-05-03T12:46:09.120Z [err]  
2019-05-03T12:46:09.121Z [err] ERR!
2019-05-03T12:46:09.121Z [err]  
2019-05-03T12:46:09.122Z [err] stack
2019-05-03T12:46:09.123Z [err]  Error: not found: make
2019-05-03T12:46:09.123Z [err] gyp
2019-05-03T12:46:09.123Z [err]  
2019-05-03T12:46:09.123Z [err] ERR!
2019-05-03T12:46:09.124Z [err]  
2019-05-03T12:46:09.124Z [err] stack
2019-05-03T12:46:09.124Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2019-05-03T12:46:09.124Z [err] gyp
2019-05-03T12:46:09.125Z [err]  
2019-05-03T12:46:09.125Z [err] ERR!
2019-05-03T12:46:09.125Z [err]  
2019-05-03T12:46:09.125Z [err] stack
2019-05-03T12:46:09.126Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2019-05-03T12:46:09.126Z [err] gyp
2019-05-03T12:46:09.126Z [err]  
2019-05-03T12:46:09.126Z [err] ERR!
2019-05-03T12:46:09.126Z [err]  
2019-05-03T12:46:09.127Z [err] stack
2019-05-03T12:46:09.127Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2019-05-03T12:46:09.127Z [err] gyp
2019-05-03T12:46:09.130Z [err]  ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2019-05-03T12:46:09.130Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2019-05-03T12:46:09.130Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2019-05-03T12:46:09.130Z [err] gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
2019-05-03T12:46:09.130Z [err] gyp ERR! System Linux 4.19.20
2019-05-03T12:46:09.130Z [err] gyp ERR!
2019-05-03T12:46:09.131Z [err]  
2019-05-03T12:46:09.131Z [err] command
2019-05-03T12:46:09.131Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-05-03T12:46:09.132Z [err] gyp
2019-05-03T12:46:09.132Z [err]  
2019-05-03T12:46:09.132Z [err] ERR!
2019-05-03T12:46:09.133Z [err]  
2019-05-03T12:46:09.133Z [err] cwd
2019-05-03T12:46:09.133Z [err]  /config/node-red/node_modules/cc-znp/node_modules/@serialport/bindings
2019-05-03T12:46:09.133Z [err] gyp
2019-05-03T12:46:09.134Z [err]  
2019-05-03T12:46:09.134Z [err] ERR!
2019-05-03T12:46:09.140Z [err]  node -v v10.14.2
2019-05-03T12:46:09.140Z [err] gyp ERR! node-gyp -v v3.8.0
2019-05-03T12:46:09.140Z [err] gyp ERR! not ok 
2019-05-03T12:46:12.630Z [err] npm
2019-05-03T12:46:12.630Z [err]  
2019-05-03T12:46:12.631Z [err] WARN
2019-05-03T12:46:12.631Z [err]  bl@0.7.0 requires a peer of stream-browserify@* but none is installed. You must install peer dependencies yourself.
2019-05-03T12:46:12.633Z [err] 
2019-05-03T12:46:12.642Z [err] npm
2019-05-03T12:46:12.642Z [err]  
2019-05-03T12:46:12.643Z [err] ERR!
2019-05-03T12:46:12.643Z [err]  
2019-05-03T12:46:12.644Z [err] code
2019-05-03T12:46:12.644Z [err]  ELIFECYCLE
2019-05-03T12:46:12.646Z [err] npm
2019-05-03T12:46:12.646Z [err]  
2019-05-03T12:46:12.646Z [err] ERR!
2019-05-03T12:46:12.647Z [err]  
2019-05-03T12:46:12.647Z [err] errno
2019-05-03T12:46:12.648Z [err]  1
2019-05-03T12:46:12.649Z [err] npm
2019-05-03T12:46:12.650Z [err]  
2019-05-03T12:46:12.650Z [err] ERR!
2019-05-03T12:46:12.651Z [err]  @serialport/bindings@2.0.7 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2019-05-03T12:46:12.652Z [err] npm
2019-05-03T12:46:12.652Z [err]  
2019-05-03T12:46:12.653Z [err] ERR!
2019-05-03T12:46:12.653Z [err]  Exit status 1
2019-05-03T12:46:12.659Z [err] npm
2019-05-03T12:46:12.659Z [err]  
2019-05-03T12:46:12.660Z [err] ERR!
2019-05-03T12:46:12.661Z [err]  
2019-05-03T12:46:12.663Z [err] npm
2019-05-03T12:46:12.665Z [err]  ERR! Failed at the @serialport/bindings@2.0.7 install script.
2019-05-03T12:46:12.665Z [err] npm 
2019-05-03T12:46:12.666Z [err] ERR!
2019-05-03T12:46:12.669Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2019-05-03T12:46:13.065Z [err] 
2019-05-03T12:46:13.066Z [err] npm
2019-05-03T12:46:13.066Z [err]  
2019-05-03T12:46:13.067Z [err] ERR!
2019-05-03T12:46:13.067Z [err]  A complete log of this run can be found in:
2019-05-03T12:46:13.067Z [err] npm
2019-05-03T12:46:13.067Z [err]  
2019-05-03T12:46:13.067Z [err] ERR!
2019-05-03T12:46:13.068Z [err]      /root/.npm/_logs/2019-05-03T12_46_12_857Z-debug.log
2019-05-03T12:46:13.106Z rc=1

**Comment by hobbyquaker** [comment]
This line
```
2019-05-03T12:46:09.123Z [err]  Error: not found: make
```
indicates that "make" is missing. 

If you're using a Debian (apt) based Distro `sudo apt install make gcc build-essential` should do the trick.

**Comment by papperone** [comment]
as I wrote initially I use NodeRed as an addon of Hass.io (Home assistant) that runs on his propietary OS (HassOS) and uses a dockers system so I cannot install anythign...
by the way, this is the only nodes I cannot install and I've errors as well in 2 others NodeRed instances on RaspberryPi under Raspbian (one here and on of my friend).

**Comment by hobbyquaker** [comment]
Regarding the install errors on raspbian: I guess its also just missing build dependencies and can be fixed easily with a simple `sudo apt install build-essential gcc make`. If this does not succeed pls show the log output.

Regarding „HassOS“ - if you can‘t install the needed build tools I see no way to use node-red-contrib-zigbee on this system. Also I think its questionable if this makes sense - zigbee2mqtt offers full fledged Hass-Integration and is imho the better choice for Hass-Users.

**Comment by papperone** [comment]
ok thanks, well the raspbian is just a test rig that I just used to test if I can install this plugin...
you coudl be right with zigbee2mqtt addon, but I do all my automations in NodeRed and have an easy way to parse the big JSON with your nodes shoudl be a big help, still can't understand why only these nodes create this problem; I've literally installed dozens of nodes and all of the works perfectly but this one....

**Comment by hobbyquaker** [comment]
the reason is that the nodes have a binary dependency that has to be build, needed for serial access to the cc253x

**Comment by papperone** [comment]
ok I see, well never mind, I will not use them then... thanks!
