### ISSUE TITLE
Controller does not work (never switches to "online")

### ISSUE THREAD

**Issue by gmarjano1975** [hobbyquaker/node-red-contrib-zigbee#149]
Hi,

I just received my new CC2531-USB-Dongle. I connected it to my Raspberrymatic (v3.55.10.20210213). 
I installed Red-Matic (v7.2.1) and the packge node-red-contrib-zigbee (v0.20.3).

I configured a controller but it never goes "Online". I checked the `/var/log/messages` and I found the following error:

```
Mar 16 15:56:56 homematic daemon.err node-red: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received type function ([Function (anonymous)])
Mar 16 15:56:56 homematic daemon.err node-red:     at Function.from (buffer.js:333:9)
Mar 16 15:56:56 homematic daemon.err node-red:     at ServerResponse.send (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/express/lib/response.js:189:22)
Mar 16 15:56:56 homematic daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/node-red-contrib-zigbee/nodes/shepherd.js:33:29
Mar 16 15:56:56 homematic daemon.err node-red:     at Layer.handle [as handle_request] (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
Mar 16 15:56:56 homematic daemon.err node-red:     at next (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
Mar 16 15:56:56 homematic daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/editor-api/lib/auth/index.js:69:28
Mar 16 15:56:56 homematic daemon.err node-red:     at complete (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/passport/lib/middleware/authenticate.js:268:13)
Mar 16 15:56:56 homematic daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/passport/lib/middleware/authenticate.js:275:15
Mar 16 15:56:56 homematic daemon.err node-red:     at pass (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/passport/lib/authenticator.js:431:14)
Mar 16 15:56:56 homematic daemon.err node-red:     at Authenticator.transformAuthInfo (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/passport/lib/authenticator.js:453:5)
Mar 16 15:56:57 homematic local0.info ReGaHss: Info: start web processing, worker thread #1 {"HTTP-Listener"} [spawnNewProcess():httpListener.cpp:208]
Mar 16 15:56:57 homematic local0.info ReGaHss: Info: recvd 287 bytes by web server #2 [ThreadFunction():httpServer.cpp:797]
```

The USB-Stick is found according `dmesg`-output.
I already set 'TTYASSIGN=ttyACM0:NC' in CuxD but that did not help either.

Is that a "real" error or can it be ignored? 

Best regards
Goran

**Comment by travelography** [comment]
have the same problem after updating from 7.1.3 to 7.2.1

Downgrading to the old version gets everything working again. --> https://github.com/rdmtc/RedMatic/releases/tag/v7.1.3

**Comment by gmarjano1975** [comment]
> 
> 
> have the same problem after updating from 7.1.3 to 7.2.1
> 
> Downgrading to the old version gets everything working again. --> https://github.com/rdmtc/RedMatic/releases/tag/v7.1.3

Thanks! That helped!

Best regards
Goran

**Comment by travelography** [comment]
However, I assume that there is a bug here. The CC2531 stick should actually work
