### ISSUE TITLE
zigbee verbindet sich nicht mehr nach Redmatic Update

### ISSUE THREAD

**Issue by Matten-Matten** [hobbyquaker/node-red-contrib-zigbee#150]
Hallo hobbyquacker,

ich habe die aktuelle redmatic version geupdatet, jedoch verbindet zigbee sich nicht mehr mit dem Stick im node steht nur closed.

ein neustart der zentrale hab ich schon durchgeführt, leider ohne Erfolg.

folgendes steht in log:

`Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-offline:7cb5ce3d.79204] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:Osram Plug 1] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:Osram Plug 4] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-offline:9f7ec881.f7cee8] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-offline:91e3a0ea.3a8bb] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-offline:3ecc3fe9.1787d] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-offline:5fb2e52.37b581c] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-offline:160627d6.73abd8] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:Osram Plug 3] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:Osram Plug 2] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:Osram Plug 6] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:Osram Plug 5] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:LEDVANCE Plug 1] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:LEDVANCE Plug 2] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:LEDVANCE Plug 3] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-offline:e9872b4e.3561] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-offline:9b960d73.3fec1] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-offline:cc047239.15b398] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-offline:b0434fa4.e0f2e8] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-controller:controller] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:Terasse E11] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-command:command] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-command:Terasse E11] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-event:Fernbedienung] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:2ba4ed06.fed7b2] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-command:command] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-command:E27 3] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-command:E27 2] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-command:E27 1] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-event:event] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:Ikea Switch 2] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:Ikea Switch 1] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:Ikea Switch 3] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:Ikea Switch Rund 1] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-converter:Ikea Switch Rund 2] missing herdsman
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-command:E27 4] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-event:event] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-command:E27 5] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-command:E27 4] missing shepherd
Mar 22 11:57:37 ccu3-webui daemon.err node-red[1287]: [zigbee-event:event] missing shepherd`

**Comment by Hoss0305** [comment]
Ich kann dieses Problem mit dem neuen node-red-contrib-zigbee V.0.20.3 nur bestätigen. Stellt sich bei mir genau so da. Kein Zugriff aus RedMatic auf den Zigbee-Stick, was mit der V.0.20.1 immer einwandfrei funktionierte. Gibt es bereits ein WorkAround für dieses Problem oder muss ich mein Backup bemühen. Würde gerne wieder die Version 0.20.1 installieren, aber wie?

**Comment by Sineos** [comment]
Kann ich bei mir nicht nachvollziehen (zzh Stick). Läuft mit RM 3.57.4.20210320 und node-red-contrib-zigbee 0.20.3

Kann es die dev.db zerschossen haben? Schonmal versucht ein Gerät zu löschen und neu zu pairen?

**Comment by Matten-Matten** [comment]
Die Dev. DB ist in Ordnung. Sobald ich die vorherige redmatic Version in meinem Fall die 7.1.3 zurück installiere. Läuft es wieder. Und alle devices sind wieder da.

**Comment by travelography** [comment]
Ich habe das Problem mit meinem CC2531 auch. Hier hat auch bereits einer einen Issue geöffnet: s/149
an anderen Stellen wird auch von dem Problem berichtet: https://homematic-forum.de/forum/viewtopic.php?f=77&t=66516

Downgrade auf 7.1.3 hat auch bei mir geholfen. Wie sieht der Rest eurer Umgebung aus? Ich benutze piVCCU3 mit Firmware 3.53.34.

**Comment by Matten-Matten** [comment]
RaspberryMatic auf Pi 4 4gb. Mit den alten Homematic Funk Modul.

**Comment by markusehrmann** [comment]
Guten Tag miteinander

kann das Problem ebenso reproduzieren - nach dem Downgrade auf Version 7.1.3 funktioniert alles wieder wie gehabt im Zusammenhang mit dem CC2531 Zigbee Stick.

Gruss Markus

**Comment by Michael-Hennemann** [comment]
Hallo Zusammen 
ich habe grade das Gleiche festgestellt. 
- Raspberrymatic auf 3.57.4.20210320 aktualisiert auf RPi 3
- RedMatic auf aarch64 7.2.1
- CC2531 USB Stick
- 
Wo genau es hängt weiss ich nicht, aber "alle" meine beiden Zigbee Devices die ich bisher angebunden hatte sind aus der Liste verschwunden und der Stick selbst wird da auch nicht mehr angezeigt. 

Viele Grüße
Michael

**Comment by Joey2go** [comment]
Hallo allerseits,
bei mir das gleiche Problem nach dem Update auf die , die alte Version 7.1.3 wieder drüber gebügelt und schon geht es wieder.
Die node-red-contrib-zigbee V.0.20.3 fubnktioniert nicht, die alte Version node-red-contrib-zigbee V.0.20.1 geht.

VG Jeroen

**Comment by FalkoDroege** [comment]
Ich habe den selben Fehler. 
Apr  5 17:42:17 homematic-raspi daemon.err node-red: TypeError: Cannot read property 'getDevices' of undefined
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/node-red-contrib-zigbee/nodes/shepherd.js:41:66
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at Layer.handle [as handle_request] (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at next (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/editor-api/lib/auth/index.js:69:28
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at complete (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/passport/lib/middleware/authenticate.js:268:13)
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/passport/lib/middleware/authenticate.js:275:15
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at pass (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/passport/lib/authenticator.js:431:14)
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at Authenticator.transformAuthInfo (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/passport/lib/authenticator.js:453:5)
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/passport/lib/middleware/authenticate.js:272:22
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at IncomingMessage.req.login.req.logIn (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/passport/lib/http/request.js:55:13)
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at Strategy.strategy.success (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/passport/lib/middleware/authenticate.js:253:13)
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at verified (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/passport-http-bearer/lib/strategy.js:126:10)
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/editor-api/lib/auth/strategies.js:37:21
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at runMicrotasks (<anonymous>)
Apr  5 17:42:17 homematic-raspi daemon.err node-red:     at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by rucksman** [comment]
Habe das gleiche problem, allerdings wird meine Hue Lampe auch nach dem Downgrade nicht gefunden. Der connector ist zwar "connected" und bei den devices gibt es einen "Coordinator". Aber die Lampe will einfach nicht mehr auftauchen (auch 3x an und aus hat nicht geholfen mit "Permit join", auch ein Klick auf TouchlinkFactoryReset blieb ohne Wirkung). Hat jemand noch einen Tip, wie ich die Lampe wieder in Betrieb nehmen kann? Betreibe das Ganze mit Raspberrymatic auf einem Pi3 und dem CC2531 Stick.

**Comment by rucksman** [comment]
Problem gelöst: ZUm Glück ist die Lampe eine Bluetooth-Lampe, also habe ich erst die Bluetooth App installiert, die Lampe gepairt und dann in der App auf Werkseinstellungen zurückgesetzt. Danach konnte ich sie wieder über PermitJoin anlernen.

**Comment by KoenigTH** [comment]
Ich habe heute auf Version 7.2.1 geupdated und habe dieselben Fehler wie der TO. Ich verwende einen CC2531 Stick. Nach dem Downgrade auf die 7.1.3 klappt wieder alles und der Stick sowie alle verbundenen Geräte können gefunden werden.

**Comment by Naviman** [comment]
Hallo zusammen,
auch ich habe das Problem, dass der CC2531 mit der Version  7.2.1 nicht mehr lauffähig war. Habe alles probiert: Stick neu geflashed, neuen Hardsman angelegt, Pairing neu angestoßen. Keine Chance. Läuft nicht.
Bin auf die alte Version 5.5.3 zurückgegangen und sofort lief wieder alles.

**Comment by Sineos** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/6517
https://github.com/Koenkk/zigbee-herdsman/commit/13eb72cb8009dae1b74f182a50a5ae44da182932

@hobbyquaker 
Würdest du eine neue Redmatik bauen mit aktualisiertem Zigbee?

**Comment by stuckis6er** [comment]
Auch ich musste von 7.2.1 zurück auf 7.1.3 jetzt funktioniert wieder alles.

**Comment by juppero** [comment]
Hi,
gibt es schon eine Lösung? Mein Zigbee-Stick ITStuff 2531 verbindet sich nicht mit NodeRed.

**Comment by juppero** [comment]
Hi,
die Lösung habe ich hier "https://homematic-forum.de/forum/viewtopic.php?f=77&t=66516#p653063" gefunden.
Änderung der PAN-ID, und es funktionierte.

**Comment by Michael-Hennemann** [comment]
> 
> 
> Hi,
> die Lösung habe ich hier "https://homematic-forum.de/forum/viewtopic.php?f=77&t=66516#p653063" gefunden.
> Änderung der PAN-ID, und es funktionierte.

Jop, das hat bei mir auch funktioniert! :-D
Ich musste meine beiden Zigbee Geräte neu "joinen" aber ich denke,  das lag daran, dass ich die im Rahmen des Troubleshootings damals einmal rausgeworfen hatte... 

Ist das jetzt eine Lösung oder ein Workaround ?

**Comment by Sineos** [comment]
> Ich musste meine beiden Zigbee Geräte neu "joinen"

Ändert man die PanID hat man ein neues Netzwerk und muss alle Geräte neu joinen.

> Ist das jetzt eine Lösung oder ein Workaround ?

Irgendwie beides 😉 
Sollte natürlich nicht notwendig sein und auch extrem lästig wenn man viele Geräte hat.

**Comment by Michael-Hennemann** [comment]
Hm, ok, zu früh gefreut. 
Heute funktionieren die Zigbee Geräte nicht mehr. Beim klick auf "Deploy" von NR erscheinen sofort einige Fehler im Debug-Log

`"Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"`

`"device unknown ${name} 0x842e14fffe626342"`

Habe mal die ganze CCU neu gestartet und auch den Stick stromlos gemacht. Bringt nichts.. sieht ein bisschen aus, als hätte der Stick schon wieder die Geräte "vergessen" 
Bis zum Update zu 7x Version im März lief das Ganze eigentlich recht stabil..   :-/

**Comment by totti1171** [comment]
Gleiches Problem - auch das ändern der ID brachte nur kurz Erfolg 

![nr](https://user-images.githubusercontent.com/42803032/127301296-2a7f4978-fac1-47a7-90ce-35fbd6a9bfa9.jpg)

**Comment by Michael-Hennemann** [comment]
> 
> 
> Gleiches Problem - auch das ändern der ID brachte nur kurz Erfolg
> 
> ![nr](https://user-images.githubusercontent.com/42803032/127301296-2a7f4978-fac1-47a7-90ce-35fbd6a9bfa9.jpg)

@totti1171 Hi, wie gesagt, nachdem ich meine Geräte neu "gejoint" habe ging es wieder. Eben hatte ich allerdings wieder so einen blöden Fall:  Hab mir einen Ikea Shortcut-Button besorgt. Zuerst wollte der nicht. Join ging, aber es ist keine msg erzeugt worden. Hin, Her, Frickel, Bastel, irgendwann hab ich die CCU mal neu gestartet, danach waren dann WIEDER alle Geräte weg und mussten neu angelernt werden. Ich trau mich grade garnicht das Ding neuzustarten :-|

**Comment by travelography** [comment]
> Gleiches Problem - auch das ändern der ID brachte nur kurz Erfolg
> 
> ![nr](https://user-images.githubusercontent.com/42803032/127301296-2a7f4978-fac1-47a7-90ce-35fbd6a9bfa9.jpg)

Das hier im Screenshot genannte Problem hat nichts mit dem Problem des TO zu tun. Der Stick ist futsch. Kannst mal versuchen in neu zu flashen. Bei mir half es allerdings nur temporär.

**Comment by Michael-Hennemann** [comment]
> 
> 
> > Gleiches Problem - auch das ändern der ID brachte nur kurz Erfolg
> > ![nr](https://user-images.githubusercontent.com/42803032/127301296-2a7f4978-fac1-47a7-90ce-35fbd6a9bfa9.jpg)
> 
> Das hier im Screenshot genannte Problem hat nichts mit dem Problem des TO zu tun. Der Stick ist futsch. Kannst mal versuchen in neu zu flashen. Bei mir half es allerdings nur temporär.

@travelography  Hm, also bei mir haben die ganzen Probleme angefangen mit dem Update. Den Fehler "Error while opening serialport" habe ich bekommen nachdem ich die PANid geändert hab.  Der war dann aber weg, nachdem ich "alle" meine beiden Geräte einmal rausgeworfen und neu gejoint hab.  Das wäre schon ein ziemlich großer Zufall, wenn der Stick kaputt gegangen wäre, in dem Moment wo ich das Update mache und anfange die config zu ändern...  Ich denke eher das ist ein Folgefehler vom Troubleshooting des eigentlichen Problems

**Comment by travelography** [comment]
Ich hatte den Fehler auch mit einer früheren Version. Der Stick lief auch immer wieder temporär. Ich habe die Geräte neu angelernt. Den Stick neu geflashed. Die CCU x-mal neugestartet. Nach einer gewissen Zeit trat aber immer wieder das hier dargestellt Problem auf. 

Du kannst ja mal nach dem Fehler googlen. Ich denke, es war Zufall, will aber auch nicht ausschließen, dass es mehrere Ursachen für das Problem gibt.

**Comment by Michael-Hennemann** [comment]
Hm, ok, Ich denke ich warte mal ab, bis mal einer das eigentliche Problem dieses threads behebt (ich kann es leider nicht) und danach schaue ich ob der Fehler mit dem serialport wieder auftritt. 
Bisher hatte ich eigentlich nur noch das Problem, dass nach einem Neustart plötzlich alle Geräte weg waren - das kann aber denke ich nichts mit dem Stick zu tun haben, nehme ich an?

**Comment by totti1171** [comment]
Bin wieder zurück auf RedMatic 7.1.3 hier scheint alles wieder normal zu laufen...

**Comment by totti1171** [comment]
> Bin wieder zurück auf RedMatic 7.1.3 hier scheint alles wieder normal zu laufen...

kleines Update - mit der alten Version läuft es seit Tagen stabil - scheint also doch ein Problem in der 7.2.1 zu sein

**Comment by Naviman** [comment]
Mich auch.

**Comment by Matten-Matten** [comment]
Hallo, mit der aktuellen zigbee version 0.21.0 funktioniert es wieder, jedoch musste ich die ganze Redmatic tar.gz laden, und via "total Commander" einige Zeilen anpassen damit die installations routine auf die V0.21.0 läd & installiert. relativ aufwändig, aber nicht unmöglich.

Gruß Matten Matten

**Comment by Lederhaut** [comment]
Hallo @Matten-Matten,
bist du sicher, dass der Update auf die neue node-red-contrib-zigbee so funktioniert hat?
Im peg-repo.json wird auf das [Source code (tar.gz)](https://github.com/hobbyquaker/node-red-contrib-zigbee/archive/refs/tags/v0.21.0.tar.gz) referenziert, zuvor war es ja ein [Compilat](https://github.com/rdmtc/RedMatic/releases/download/v7.2.1/redmatic-pkg-node-red-contrib-zigbee-0.20.3.tar.gz) vom Release https://github.com/rdmtc/RedMatic/releases/tag/v7.2.1.
Welche Version zeigt es denn in Node-RED an?

Viele Grüße

**Comment by Matten-Matten** [comment]
@Lederhaut 
Nein das allein hat tatsächlich nicht funktioniert.
Ich hatte zuvor die die Dateien aus node-red-contrib-zigbee-0.21.0 entpackt und via filezilla in den ordner `contrib zigbee ` kopiert und ersetzt.

Ihr könnt das gerne auch testen aber auf einige Gefahr! Vorher ein Backup ziehen!!! Ist ja immer wichtig.

**Comment by Christchoper** [comment]
Hallo Zusammen,
@hobbyquaker  gerne bestätige ich ebenfalls das Verhalten und wollte nachfragen, ob das Update mit der nächsten Version mit an Bord ist?
Grüsse,
Chris

**Comment by Lederhaut** [comment]
Hallo nochmal,
das Problem liegt eventuell daran:
https://github.com/hobbyquaker/node-red-contrib-zigbee/issues/160
dort ist auch schon ein fix drin.
man kann auf der CCU3 die Datei /usr/local/addons/redmatic/lib/node_modules/node-red-contrib-zigbee/nodes/shepherd.js die Datei fixen.
Bei mir hatte es das Problem gelöst.
