### ISSUE TITLE
TouchlinkFactoryReset goes in error

### ISSUE THREAD

**Issue by ckhmer1** [hobbyquaker/node-red-contrib-zigbee#152]
Hi,
first of all, thanks for your great work.
Unfortunately, it seems that the touchlink factory reset button is not working.
I've tried to reset a bulb, and if I press the TouchlinkFactoryReset button, I get the following exception on Node-RED log:

```
Sat, 05 Jun 2021 08:44:36 GMT express:router dispatching GET /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
Sat, 05 Jun 2021 08:44:36 GMT express:router query  : /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
Sat, 05 Jun 2021 08:44:36 GMT express:router expressInit  : /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
Sat, 05 Jun 2021 08:44:36 GMT express:router serveStatic  : /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
Sat, 05 Jun 2021 08:44:36 GMT send stat "/usr/src/node-red/node_modules/@node-red/editor-client/public/zigbee-shepherd/status"
Sat, 05 Jun 2021 08:44:36 GMT express:router mounted_app  : /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
Sat, 05 Jun 2021 08:44:36 GMT express:router dispatching GET /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
Sat, 05 Jun 2021 08:44:36 GMT express:router query  : /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
Sat, 05 Jun 2021 08:44:36 GMT express:router expressInit  : /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
Sat, 05 Jun 2021 08:44:36 GMT express:router mounted_app  : /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
Sat, 05 Jun 2021 08:44:36 GMT express:router dispatching GET /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
Sat, 05 Jun 2021 08:44:36 GMT express:router query  : /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
Sat, 05 Jun 2021 08:44:36 GMT express:router expressInit  : /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
(node:18) UnhandledPromiseRejectionWarning: Error: Write for 'BUFFER' not available
    at BuffaloZnp.write (/data/node_modules/zigbee-herdsman/dist/buffalo/buffalo.js:259:19)
    at ZpiObject.createPayloadBuffer (/data/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/zpiObject.js:87:21)
    at ZpiObject.toUnpiFrame (/data/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/zpiObject.js:38:29)
    at Znp.<anonymous> (/data/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:279:34)
    at Generator.next (<anonymous>)
    at /data/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/data/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at Object.queue.execute [as func] (/data/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:277:41)
    at Queue.<anonymous> (/data/node_modules/zigbee-herdsman/dist/utils/queue.js:29:46)
    at Generator.next (<anonymous>)
    at /data/node_modules/zigbee-herdsman/dist/utils/queue.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/data/node_modules/zigbee-herdsman/dist/utils/queue.js:4:12)
    at Queue.executeNext (/data/node_modules/zigbee-herdsman/dist/utils/queue.js:24:16)
    at Promise (/data/node_modules/zigbee-herdsman/dist/utils/queue.js:20:18)
    at new Promise (<anonymous>)
    at Queue.execute (/data/node_modules/zigbee-herdsman/dist/utils/queue.js:18:16)
    at Znp.request (/data/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:277:27)
    at ZStackAdapter.<anonymous> (/data/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:709:32)
    at Generator.next (<anonymous>)
    at /data/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:27:71
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
Sat, 05 Jun 2021 08:44:37 GMT express:router dispatching GET /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
Sat, 05 Jun 2021 08:44:37 GMT express:router query  : /zigbee-shepherd/status?id=2c23fd8f.e8a7e2
```

**Comment by FrankGiesecke** [comment]
Is there any solution for this problem?
Is it possible to send the touchlink command using one of the nodes provided by node-red-contrib-zigbee?
