### ISSUE TITLE
Update auf 0.21.0 geht nicht

### ISSUE THREAD

**Issue by hannoverRed** [hobbyquaker/node-red-contrib-zigbee#159]
node-red-contrib-zigbee
0.20.3
 Update auf 0.21.0 geht nicht

CCU3

**Comment by Muelli64** [comment]
node-red-contrib-zigbee

Update from 0.20.3 to 0.21.0 is not working

RedMatic Version 7.2.1
Raspberrymatic 3.59.6.20211009
Raspberry-Pi 3B


**Logfile:**

-----------------------------------------------------------
2021-11-17T21:26:35.361Z installieren : node-red-contrib-zigbee 0.21.0

2021-11-17T21:26:35.811Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-zigbee@0.21.0
2021-11-17T21:27:12.835Z [err] npm
2021-11-17T21:27:12.839Z [err]  
2021-11-17T21:27:12.840Z [err] WARN
2021-11-17T21:27:12.841Z [err]  
2021-11-17T21:27:12.841Z [err] deprecated
2021-11-17T21:27:12.842Z [err]  vis@4.21.0: Please consider using https://github.com/visjs
2021-11-17T21:27:22.051Z [err] npm
2021-11-17T21:27:22.052Z [err]  ERR! code 1
2021-11-17T21:27:22.053Z [err] npm 
2021-11-17T21:27:22.053Z [err] ERR! path /usr/local/addons/redmatic/var/node_modules/node-red-contrib-zigbee/node_modules/zigbee-herdsman/node_modules/@serialport/bindings
2021-11-17T21:27:22.064Z [err] npm 
2021-11-17T21:27:22.065Z [err] ERR! command failed
2021-11-17T21:27:22.065Z [err] npm ERR!
2021-11-17T21:27:22.065Z [err]  command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2021-11-17T21:27:22.065Z [err] npm
2021-11-17T21:27:22.065Z [err]  ERR! prebuild-install WARN install No prebuilt binaries found (target=14.16.0 runtime=node arch=arm64 libc= platform=linux)
2021-11-17T21:27:22.065Z [err] npm 
2021-11-17T21:27:22.066Z [err] ERR! gyp info it worked if it ends with ok
2021-11-17T21:27:22.066Z [err] npm 
2021-11-17T21:27:22.066Z [err] ERR! gyp info using node-gyp@7.1.2
2021-11-17T21:27:22.066Z [err] npm ERR!
2021-11-17T21:27:22.066Z [err]  gyp info using node@14.16.0 | linux | arm64
2021-11-17T21:27:22.066Z [err] npm ERR! gyp ERR! find Python 
2021-11-17T21:27:22.066Z [err] npm
2021-11-17T21:27:22.066Z [err]  ERR! gyp ERR! find Python Python is not set from command line or npm configuration
2021-11-17T21:27:22.066Z [err] npm 
2021-11-17T21:27:22.067Z [err] ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2021-11-17T21:27:22.067Z [err] npm ERR!
2021-11-17T21:27:22.077Z [err]  gyp ERR! find Python checking if "python3" can be used
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python checking if "python2" can be used
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python - "python2" is not in PATH or produced an error
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python 
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python **********************************************************
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python you can try one of the following options:
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python For more information consult the documentation at:
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python **********************************************************
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! find Python 
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! configure error 
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:302:47)
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:266:16)
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! stack     at exithandler (child_process.js:315:5)
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! System Linux 5.10.60
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-zigbee/node_modules/zigbee-herdsman/node_modules/@serialport/bindings
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! node -v v14.16.0
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! node-gyp -v v7.1.2
2021-11-17T21:27:22.077Z [err] npm ERR! gyp ERR! not ok
2021-11-17T21:27:22.402Z [err] 
2021-11-17T21:27:22.403Z [err] npm ERR! A complete log of this run can be found in:
2021-11-17T21:27:22.403Z [err] npm ERR!     /usr/local/addons/redmatic/var/npm-cache/_logs/2021-11-17T21_27_22_130Z-debug.log
2021-11-17T21:27:22.603Z rc=1

**Comment by Sineos** [comment]
https://github.com/rdmtc/RedMatic/wiki/Node-Installation#nodes-mit-bin%C3%A4rmodulen

**Comment by hannoverRed** [comment]
guten morgen,

kann mir jemand da weiter helfen?

`
-----------------------------------------------------------
2021-11-20T05:21:01.312Z installieren : node-red-contrib-zigbee 0.21.0

2021-11-20T05:21:02.027Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-zigbee@0.21.0
2021-11-20T05:22:56.017Z [err] npm WARN deprecated vis@4.21.0: Please consider using https://github.com/visjs
2021-11-20T05:23:16.352Z [err] npm ERR! code 1
2021-11-20T05:23:16.352Z [err] npm ERR! path /usr/local/addons/redmatic/var/node_modules/node-red-contrib-zigbee/node_modules/zigbee-herdsman/node_modules/@serialport/bindings
2021-11-20T05:23:16.352Z [err] npm ERR! command failed
2021-11-20T05:23:16.352Z [err] npm ERR! command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2021-11-20T05:23:16.352Z [err] npm ERR! prebuild-install WARN install No prebuilt binaries found (target=14.16.0 runtime=node arch=arm libc= platform=linux)
2021-11-20T05:23:16.352Z [err] npm ERR! gyp info it worked if it ends with ok
2021-11-20T05:23:16.352Z [err] npm ERR! gyp info using node-gyp@7.1.2
2021-11-20T05:23:16.352Z [err] npm ERR! gyp info using node@14.16.0 | linux | arm
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python 
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python checking if "python3" can be used
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python checking if "python2" can be used
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python - "python2" is not in PATH or produced an error
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python 
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python **********************************************************
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python you can try one of the following options:
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python For more information consult the documentation at:
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python **********************************************************
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! find Python 
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! configure error 
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:302:47)
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:266:16)
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! stack     at exithandler (child_process.js:315:5)
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! System Linux 4.14.34
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-zigbee/node_modules/zigbee-herdsman/node_modules/@serialport/bindings
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! node -v v14.16.0
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! node-gyp -v v7.1.2
2021-11-20T05:23:16.352Z [err] npm ERR! gyp ERR! not ok
2021-11-20T05:23:17.334Z [err] 
2021-11-20T05:23:17.334Z [err] npm ERR! A complete log of this run can be found in:
2021-11-20T05:23:17.334Z [err] npm ERR!     /usr/local/addons/redmatic/var/npm-cache/_logs/2021-11-20T05_23_16_303Z-debug.log
2021-11-20T05:23:17.369Z rc=1`

**Comment by Sineos** [comment]
> kann mir jemand da weiter helfen?

Ja, den Link lesen, den ich über deinen letzten Post platziert habe.
node-red-contrib-zigbee ist ein Binärpaket und lässt sich nur installieren, wenn ein spezielles Paket von @hobbyquaker gebaut wird und in einer neuen Redmatic Version zur Verfügung gestellt wird

**Comment by kender65** [comment]
Aloha!
Ich habe node-red auf einem "normalen" Raspi 4 laufen, daran angeschlossen ein zzh (CC2652R Stick).
Es waren ein paar wenige Geräte (Lichtsensor, Steckdosen, etc.) angeschlossen und haben tadellos funktioniert.
Nach dem Update von node-red-contrib-zigbee von 0.20.3 auf 0.21.0 und dem anschließenden Neustart von node-red erscheint in regelmäßigen Abständen (ca. 10 Sekunden) die folgende Fehlermeldung:
Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
Die Geräte funktionieren alle nicht mehr.

Diverse Neustarts des Raspi mit und ohne Stick, stoppen und starten von node-red haben nicht zum Erfolg geführt.
Da ich noch nicht so viele Geräte gepaired hatte, habe ich alle Verwendungen des Controllerknotens und den Controller selber gelöscht; anschließend node-red gestoppt, Raspi rebootet, node-red neu gestartet. Beim Versuch einen neuen Controller anzulegen erscheint nach wie vor die gleiche Fehlermeldung. Auch unterschiedliche Network-Keys und / oder PanIds führen nicht zum Erfolg.
Der Stick selber wird am USB0 erkannt...
Wo kann ich noch suchen bzw. was noch probieren?
Vielen Dank vorab!

**Comment by hectorzeta** [comment]
Hi @hobbyquaker,

Do you plan to build the package for Redmatic?

**Comment by dbMerkel** [comment]
Hallo @hobbyquaker , ich habe das selbe Problem und kann kein Update ausführen. 
Können Sie mir da helfen?

**Comment by hannoverRed** [comment]
@dbMerkel viel glück, da kommt seit langem keine Reaktion mehr. habe den Stick zurück geschickt und lese mit node Red meine Zigbee Geräte über Smart Life aus

**Comment by Schroeder0815** [comment]
Hi, 
habe leider auch zu spät gemerkt, dass OTA Update noch nicht implementiert ist.
Somit musste es auch scheitern….

Weiß jemand wie man es wieder zum laufen bekommt ohne alles zu deinstallieren und neu einrichten zu müssen?

Danke und Gruß…
