### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by dedepene** [hobbyquaker/node-red-contrib-zigbee#47]
Hi,

Trying to install in node-red running in a docker as part of a hassio (home assistant) install and getting a bunch of errors. A little help please?

`-----------------------------------------------------------
2019-09-16T11:18:00.811Z Install : node-red-contrib-zigbee 0.8.0

2019-09-16T11:18:03.219Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-zigbee@0.8.0
2019-09-16T11:18:11.671Z [err] npm
2019-09-16T11:18:11.672Z [err]  WARN deprecated
2019-09-16T11:18:11.672Z [err]  vis@4.21.0: Please consider using https://github.com/visjs
2019-09-16T11:19:14.730Z [out] 
2019-09-16T11:19:14.730Z [out] > @serialport/bindings@2.0.8 install /config/node-red/node_modules/zigbee-herdsman/node_modules/@serialport/bindings
2019-09-16T11:19:14.730Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2019-09-16T11:19:14.730Z [out] 
2019-09-16T11:19:17.445Z [err] prebuild-install
2019-09-16T11:19:17.446Z [err]  WARN install
2019-09-16T11:19:17.446Z [err]  No prebuilt binaries found (target=10.16.3 runtime=node arch=x64 libc=musl platform=linux)
2019-09-16T11:19:20.977Z [err] gyp
2019-09-16T11:19:20.979Z [err]  
2019-09-16T11:19:20.979Z [err] ERR!
2019-09-16T11:19:20.979Z [err]  build error
2019-09-16T11:19:20.979Z [err]  
2019-09-16T11:19:20.981Z [err] gyp
2019-09-16T11:19:20.981Z [err]  
2019-09-16T11:19:20.982Z [err] ERR! 
2019-09-16T11:19:20.982Z [err] stack Error: not found: make
2019-09-16T11:19:20.982Z [err] gyp
2019-09-16T11:19:20.982Z [err]  ERR!
2019-09-16T11:19:20.982Z [err]  stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2019-09-16T11:19:20.982Z [err] gyp
2019-09-16T11:19:20.983Z [err]  ERR!
2019-09-16T11:19:20.983Z [err]  stack
2019-09-16T11:19:20.983Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2019-09-16T11:19:20.983Z [err] gyp
2019-09-16T11:19:20.983Z [err]  ERR! 
2019-09-16T11:19:20.983Z [err] stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2019-09-16T11:19:20.983Z [err] gyp 
2019-09-16T11:19:20.983Z [err] ERR! 
2019-09-16T11:19:20.984Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2019-09-16T11:19:20.984Z [err] gyp 
2019-09-16T11:19:20.984Z [err] ERR! 
2019-09-16T11:19:20.984Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2019-09-16T11:19:20.984Z [err] gyp 
2019-09-16T11:19:20.984Z [err] ERR! 
2019-09-16T11:19:20.984Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2019-09-16T11:19:20.985Z [err] gyp 
2019-09-16T11:19:20.985Z [err] ERR! 
2019-09-16T11:19:20.985Z [err] stack     at FSReqWrap.oncomplete (fs.js:153:21)
2019-09-16T11:19:20.986Z [err] gyp
2019-09-16T11:19:20.986Z [err]  ERR!
2019-09-16T11:19:20.986Z [err]  System
2019-09-16T11:19:20.986Z [err]  Linux 4.15.0-62-generic
2019-09-16T11:19:20.987Z [err] gyp
2019-09-16T11:19:20.987Z [err]  ERR! 
2019-09-16T11:19:20.987Z [err] command
2019-09-16T11:19:20.987Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-09-16T11:19:20.987Z [err] gyp
2019-09-16T11:19:20.988Z [err]  ERR!
2019-09-16T11:19:20.988Z [err]  cwd
2019-09-16T11:19:20.988Z [err]  /config/node-red/node_modules/zigbee-herdsman/node_modules/@serialport/bindings
2019-09-16T11:19:20.988Z [err] gyp 
2019-09-16T11:19:20.988Z [err] ERR! 
2019-09-16T11:19:20.988Z [err] node -v v10.16.3
2019-09-16T11:19:20.989Z [err] gyp 
2019-09-16T11:19:20.989Z [err] ERR! 
2019-09-16T11:19:20.989Z [err] node-gyp -v v3.8.0
2019-09-16T11:19:20.989Z [err] gyp
2019-09-16T11:19:20.989Z [err]  ERR! 
2019-09-16T11:19:20.990Z [err] not ok 
2019-09-16T11:19:34.046Z [err] npm
2019-09-16T11:19:34.046Z [err]  WARN
2019-09-16T11:19:34.046Z [err]  optional
2019-09-16T11:19:34.046Z [err]  SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/zigbee-herdsman/node_modules/fsevents):
2019-09-16T11:19:34.047Z [err] npm
2019-09-16T11:19:34.047Z [err]  
2019-09-16T11:19:34.047Z [err] WARN 
2019-09-16T11:19:34.047Z [err] notsup
2019-09-16T11:19:34.047Z [err]  SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2019-09-16T11:19:34.049Z [err] 
2019-09-16T11:19:34.076Z [err] npm ERR! code ELIFECYCLE
2019-09-16T11:19:34.076Z [err] npm ERR! errno 1
2019-09-16T11:19:34.076Z [err] npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2019-09-16T11:19:34.076Z [err] npm ERR! Exit status 1
2019-09-16T11:19:34.076Z [err] npm ERR! 
2019-09-16T11:19:34.076Z [err] npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
2019-09-16T11:19:34.076Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-09-16T11:19:34.409Z [err] 
2019-09-16T11:19:34.409Z [err] npm ERR! A complete log of this run can be found in:
2019-09-16T11:19:34.409Z [err] npm ERR!     /root/.npm/_logs/2019-09-16T11_19_34_286Z-debug.log
2019-09-16T11:19:34.429Z rc=1`

**Comment by hobbyquaker** [comment]
there are tools missing on your system that are needed to build the serialport module. If you're on a debian based distro you can try `sudo apt-get install build-essential python2.7-minimal`

**Comment by dedepene** [comment]
> there are tools missing on your system that are needed to build the serialport module. If you're on a debian based distro you can try `sudo apt-get install build-essential python2.7-minimal`

I have Ubuntu 18.04 LTS and node-red is running in a docker container, alongside hassio. I do have both python and build-essential installed on the host ubuntu system, yet i get these errors. :(

**Comment by hobbyquaker** [comment]
then you have the build tools on your host system - but not inside the container where you try to install the package.

**Comment by dedepene** [comment]
OK, thanks for the pointer. Apparently the container is Alpine Linux, and I ran in it:

```
apk update
&& apk add --virtual build-dependencies
build-base
gcc
wget
git
```

Still getting a bunch of errors. Any specific instructions when installing in Alpine container - i.e. just about every hass.io deployment?

`root@a0d7b954-nodered.local.hass.io:/opt$ npm install node-red-contrib-zigbee
npm WARN deprecated vis@4.21.0: Please consider using https://github.com/visjs

> bcrypt@3.0.6 install /opt/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v64-linux-x64-musl.tar.gz
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.6 and node@10.16.3 (node-v64 ABI, musl) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.15.0-64-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/opt/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/opt/node_modules/bcrypt/lib/binding" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /opt/node_modules/bcrypt
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/opt/node_modules/bcrypt/lib/binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.15.0-64-generic
node-pre-gyp ERR! command "/usr/bin/node" "/opt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/opt/node_modules/bcrypt/lib/binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

> @serialport/bindings@2.0.8 install /opt/node_modules/zigbee-herdsman/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.16.3 runtime=node arch=x64 libc=musl platform=linux)
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.15.0-64-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/node_modules/zigbee-herdsman/node_modules/@serialport/bindings
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/zigbee-herdsman/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@3.0.6 (node_modules/bcrypt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-19T07_56_48_459Z-debug.log`

**Comment by dedepene** [comment]
hello?

**Comment by hobbyquaker** [comment]
```
gyp ERR! stack Error: not found: make
```

**Comment by dedepene** [comment]
> ```
> gyp ERR! stack Error: not found: make
> ```

Duh. Thanks!

But you could probably add a line or two in the readme on how to set up a node-red hassio container before installing. Apparently, the hassio Alpine linux container does not come with build-base installed.
