### ISSUE TITLE
error: TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/node-red-contrib-zigbee#64]
When I will send command to converter:
![image](https://user-images.githubusercontent.com/12692680/67333158-609a6300-f520-11e9-9fb8-c50abb5abc27.png)

I get the error: `TypeError: Cannot read property 'match' of undefined`

```
TypeError: Cannot read property 'match' of undefined
    at ZigbeeConverter.on.msg [as _inputCallback] (/usr/local/addons/redmatic/lib/node_modules/node-red-contrib-zigbee/nodes/converter.js:63:50)
    at ZigbeeConverter.Node._emitInput (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate._onImmediate (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at runCallback (timers.js:705:18)    at tryOnImmediate (timers.js:676:5)    at processImmediate (timers.js:658:5)
```

**Comment by Hypnos3** [comment]
der "get topic" im converter war bei mir nicht gesetzt (Fehler sollte man eventuell abfangen).
