### ISSUE TITLE
Cant install plugin into Home Assistant

### ISSUE THREAD

**Issue by domnich** [hobbyquaker/node-red-contrib-zigbee#97]
Hi there! During installation Im see next error in my log:

-----------------------------------------------------------
2020-01-10T12:59:29.174Z Install : node-red-contrib-zigbee 0.17.0

2020-01-10T12:59:29.321Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-zigbee@0.17.0
2020-01-10T12:59:38.074Z [err] npm
2020-01-10T12:59:38.075Z [err]  WARN deprecated vis@4.21.0: Please consider using https://github.com/visjs
2020-01-10T13:01:57.603Z [out] 
2020-01-10T13:01:57.603Z [out] > @serialport/bindings@8.0.4 install /config/node-red/node_modules/zigbee-herdsman/node_modules/@serialport/bindings
2020-01-10T13:01:57.603Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2020-01-10T13:01:57.603Z [out] 
2020-01-10T13:01:59.322Z [err] prebuild-install
2020-01-10T13:01:59.322Z [err]  WARN install
2020-01-10T13:01:59.323Z [err]  No prebuilt binaries found (target=12.14.0 runtime=node arch=arm libc=musl platform=linux)
2020-01-10T13:02:02.293Z [err] gyp
2020-01-10T13:02:02.294Z [err]  
2020-01-10T13:02:02.294Z [err] ERR! build error
2020-01-10T13:02:02.294Z [err]  
2020-01-10T13:02:02.297Z [err] gyp
2020-01-10T13:02:02.297Z [err]  ERR!
2020-01-10T13:02:02.298Z [err]  stack
2020-01-10T13:02:02.298Z [err]  Error: not found: make
2020-01-10T13:02:02.298Z [err] gyp ERR!
2020-01-10T13:02:02.299Z [err]  stack
2020-01-10T13:02:02.299Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-01-10T13:02:02.299Z [err] gyp 
2020-01-10T13:02:02.299Z [err] ERR! 
2020-01-10T13:02:02.299Z [err] stack
2020-01-10T13:02:02.299Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-01-10T13:02:02.299Z [err] gyp
2020-01-10T13:02:02.300Z [err]  
2020-01-10T13:02:02.300Z [err] ERR!
2020-01-10T13:02:02.300Z [err]  stack
2020-01-10T13:02:02.300Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-01-10T13:02:02.300Z [err] gyp 
2020-01-10T13:02:02.300Z [err] ERR!
2020-01-10T13:02:02.300Z [err]  stack
2020-01-10T13:02:02.301Z [err]      at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-01-10T13:02:02.301Z [err] gyp 
2020-01-10T13:02:02.301Z [err] ERR!
2020-01-10T13:02:02.301Z [err]  stack
2020-01-10T13:02:02.301Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-01-10T13:02:02.301Z [err] gyp 
2020-01-10T13:02:02.301Z [err] ERR! 
2020-01-10T13:02:02.302Z [err] stack
2020-01-10T13:02:02.302Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-01-10T13:02:02.302Z [err] gyp
2020-01-10T13:02:02.302Z [err]  
2020-01-10T13:02:02.302Z [err] ERR! 
2020-01-10T13:02:02.302Z [err] stack
2020-01-10T13:02:02.302Z [err]      at FSReqCallback.oncomplete (fs.js:158:21)
2020-01-10T13:02:02.303Z [err] gyp
2020-01-10T13:02:02.303Z [err]  ERR! 
2020-01-10T13:02:02.303Z [err] System Linux 4.14.98-v7
2020-01-10T13:02:02.304Z [err] gyp
2020-01-10T13:02:02.304Z [err]  ERR!
2020-01-10T13:02:02.304Z [err]  command
2020-01-10T13:02:02.304Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-01-10T13:02:02.304Z [err] gyp
2020-01-10T13:02:02.305Z [err]  ERR!
2020-01-10T13:02:02.305Z [err]  cwd
2020-01-10T13:02:02.305Z [err]  /config/node-red/node_modules/zigbee-herdsman/node_modules/@serialport/bindings
2020-01-10T13:02:02.305Z [err] gyp 
2020-01-10T13:02:02.305Z [err] ERR!
2020-01-10T13:02:02.305Z [err]  node -v
2020-01-10T13:02:02.305Z [err]  v12.14.0
2020-01-10T13:02:02.306Z [err] gyp
2020-01-10T13:02:02.306Z [err]  ERR!
2020-01-10T13:02:02.306Z [err]  node-gyp -v
2020-01-10T13:02:02.306Z [err]  v5.0.5
2020-01-10T13:02:02.306Z [err] gyp
2020-01-10T13:02:02.306Z [err]  ERR!
2020-01-10T13:02:02.306Z [err]  
2020-01-10T13:02:02.307Z [err] not ok 
2020-01-10T13:02:15.741Z [err] npm
2020-01-10T13:02:15.742Z [err]  WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/zigbee-herdsman/node_modules/fsevents):
2020-01-10T13:02:15.742Z [err] npm
2020-01-10T13:02:15.742Z [err]  WARN notsup
2020-01-10T13:02:15.742Z [err]  SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
2020-01-10T13:02:15.743Z [err] npm
2020-01-10T13:02:15.743Z [err]  WARN optional
2020-01-10T13:02:15.744Z [err]  SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/zigbee-herdsman-converters/node_modules/fsevents):
2020-01-10T13:02:15.744Z [err] npm
2020-01-10T13:02:15.744Z [err]  WARN
2020-01-10T13:02:15.744Z [err]  notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
2020-01-10T13:02:15.746Z [err] 
2020-01-10T13:02:15.800Z [err] npm ERR! code ELIFECYCLE
2020-01-10T13:02:15.800Z [err] npm ERR! errno 1
2020-01-10T13:02:15.801Z [err] npm
2020-01-10T13:02:15.801Z [err]  ERR! @serialport/bindings@8.0.4 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2020-01-10T13:02:15.801Z [err] npm
2020-01-10T13:02:15.802Z [err]  ERR!
2020-01-10T13:02:15.802Z [err]  Exit status 1
2020-01-10T13:02:15.802Z [err] npm 
2020-01-10T13:02:15.802Z [err] ERR! 
2020-01-10T13:02:15.802Z [err] npm ERR!
2020-01-10T13:02:15.802Z [err]  Failed at the @serialport/bindings@8.0.4 install script.
2020-01-10T13:02:15.802Z [err] npm
2020-01-10T13:02:15.802Z [err]  ERR!
2020-01-10T13:02:15.803Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-01-10T13:02:16.068Z [err] 
2020-01-10T13:02:16.069Z [err] npm ERR! A complete log of this run can be found in:
2020-01-10T13:02:16.069Z [err] npm 
2020-01-10T13:02:16.069Z [err] ERR!     /root/.npm/_logs/2020-01-10T13_02_15_986Z-debug.log
2020-01-10T13:02:16.115Z rc=1

Any ideas how this problem might be solved ? Thanks!

**Comment by Sineos** [comment]
node-serialport fails to be fetched and or built. On which platform / operating system are you trying to install?

**Comment by domnich** [comment]
Im using raspberry pi 3 B+ with installed Hass.io (HassOS 2.12) on it. My Home assistant version is 0.103.6 and Node Red add-on (6 .0.1). Feel free to ask any info you need =)

**Comment by Sineos** [comment]
Sorry, can't comment on HassOS but the error message indicates that npm is not able to build the required node-serialport because it does not find the needed build tools, e.g. gcc, make etc

`2020-01-10T13:02:02.298Z [err] Error: not found: make`

On a bare Ubuntu/Debian distro a simple `apt install build-essential` would most likely get you going.

Also this special linux is probably the reason why no pre-built modules are found:

`2020-01-10T13:01:59.323Z [err] No prebuilt binaries found (target=12.14.0 runtime=node arch=arm libc=musl platform=linux)`

**Comment by ChrisShUK** [comment]
Hi,
I am also having the same problem. I am running Debian, with build-essentials installed. Using Home Assistant and the Node Red plugin, i am trying to install this inside node-red and it also complains about not being able to find make.
Even though make is installed. 
It is running in a docker, maybe that is the problem ?
thanks
Chris

**Comment by Sineos** [comment]
Try `which make` in the docker environment to see if make is found. I did not try it in a docker so far, so I cannot give any further advice.

**Comment by domnich** [comment]
During installation process first error is:

2020-02-28T14:51:13.467Z [err] npm
2020-02-28T14:51:13.468Z [err]  WARN deprecated vis@4.21.0: Please consider using https://github.com/visj

Im not an expert here but maybe its possible to change **vis** dependency which is used in node-red-contrib-zigbee to the newer one which is provided here https://github.com/visj ?

Even if it will not help you will get rid from the annoying error which exist in installation process

**Comment by sniperxnl** [comment]
Anyone have it working?

**Comment by ChrisShUK** [comment]
HI

To give you an update i tried "which make" and it was not install so i added to the config file under the  system_packages section. 

It then complained about g++ not been installed, so i added g++ to there too.
Now node red will not start, giving an error when installing g++....

(1/1) Installing make (4.2.1-r2)
Executing busybox-1.31.1-r9.trigger
OK: 132 MiB in 51 packages
  musl-1.1.24-r1:
ERROR: unsatisfiable constraints:
    breaks: musl-dev-1.1.24-r2[musl=1.1.24-r2]
